# Generated by Django 6.0.7 on 2026-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=30, unique=True)),
                ("model", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("capacity", models.PositiveIntegerField(help_text="Capacity in KG")),
                ("odometer", models.PositiveIntegerField(default=0)),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("On Trip", "On Trip"),
                            ("In Shop", "In Shop"),
                            ("Retired", "Retired"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
