# Generated by Django 6.0.7 on 2026-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_expiry", models.DateField()),
                ("safety_score", models.PositiveIntegerField(default=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("On Trip", "On Trip"),
                            ("Off Duty", "Off Duty"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
